In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
%gui qt

In [3]:
import numpy as np
from spiketag.base import probe
from spiketag.view import probe_view

/disk0/anaconda3/lib/python3.7/site-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
/disk0/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [4]:
prb_bowtie_LL = probe(shank_no=6, prb_type='bow_tie')

prb_bowtie_LL.shanks[0].l = [59,60,10,58,12,11,57,56]
prb_bowtie_LL.shanks[0].r = [5,52,3,54,53,4,13,2,55]
prb_bowtie_LL.shanks[0].xl = -100.
prb_bowtie_LL.shanks[0].yl = 20
prb_bowtie_LL.shanks[0].xr = -80.
prb_bowtie_LL.shanks[0].yr = 5

prb_bowtie_LL.shanks[1].l = [15,63,48,47,0,61,9,14,62,6]
prb_bowtie_LL.shanks[1].r = [8, 1,51,50,18,34,31,25,33,17,22,49]
prb_bowtie_LL.shanks[1].xl = -10.
prb_bowtie_LL.shanks[1].yl = 15
prb_bowtie_LL.shanks[1].xr = 10.
prb_bowtie_LL.shanks[1].yr = 0 

prb_bowtie_LL.shanks[2].l = [39,38,20,45,44,24,7,32,16,23,46,30]
prb_bowtie_LL.shanks[2].r = [19,37,21,35,36,26,29,40,27,42,41,28,43]
prb_bowtie_LL.shanks[2].xl = 80.
prb_bowtie_LL.shanks[2].yl = 10 
prb_bowtie_LL.shanks[2].xr = 100.
prb_bowtie_LL.shanks[2].yr = -5

prb_bowtie_LL.shanks[3].l = [123,124,74,122,76,75,121,120]
prb_bowtie_LL.shanks[3].r = [69,116,67,118,117,68,77,66,119]
prb_bowtie_LL.shanks[3].xl = 350
prb_bowtie_LL.shanks[3].yl = 10
prb_bowtie_LL.shanks[3].xr = 370.
prb_bowtie_LL.shanks[3].yr = -5

prb_bowtie_LL.shanks[4].l = [79,127,112,111,64,125,73,78,126,70]
prb_bowtie_LL.shanks[4].r = [72,65,115,114,82,98,95,89,97,81,86,113]
prb_bowtie_LL.shanks[4].xl = 260.
prb_bowtie_LL.shanks[4].yl = 15
prb_bowtie_LL.shanks[4].xr = 280.
prb_bowtie_LL.shanks[4].yr = 0 

prb_bowtie_LL.shanks[5].l = [103,102,84,109,108,88,71,96,80,87,110,94]
prb_bowtie_LL.shanks[5].r = [83,101,85,99,100,90,93,104,91,106,105,92,107]
prb_bowtie_LL.shanks[5].xl = 170.
prb_bowtie_LL.shanks[5].yl = 20
prb_bowtie_LL.shanks[5].xr = 190.
prb_bowtie_LL.shanks[5].yr = 5

In [5]:
prb_bowtie_LL.auto_pos()
prb_bowtie_LL.mapping

OrderedDict([(59, array([-100.,   20.])),
             (60, array([-100.,   30.])),
             (10, array([-100.,   40.])),
             (58, array([-100.,   50.])),
             (12, array([-100.,   60.])),
             (11, array([-100.,   70.])),
             (57, array([-100.,   80.])),
             (56, array([-100.,   90.])),
             (5, array([-80.,   5.])),
             (52, array([-80.,  15.])),
             (3, array([-80.,  25.])),
             (54, array([-80.,  35.])),
             (53, array([-80.,  45.])),
             (4, array([-80.,  55.])),
             (13, array([-80.,  65.])),
             (2, array([-80.,  75.])),
             (55, array([-80.,  85.])),
             (15, array([-10.,  15.])),
             (63, array([-10.,  25.])),
             (48, array([-10.,  35.])),
             (47, array([-10.,  45.])),
             (0, array([-10.,  55.])),
             (61, array([-10.,  65.])),
             (9, array([-10.,  75.])),
             (14, array([-10.,

In [6]:
prb_bowtie_LL.mapping[5]  += np.array([-10,2])
prb_bowtie_LL.mapping[52] += np.array([-2, 0])
prb_bowtie_LL.mapping[8]  += np.array([-10,2])
prb_bowtie_LL.mapping[1]  += np.array([-2, 0])
prb_bowtie_LL.mapping[19] += np.array([-10,2])
prb_bowtie_LL.mapping[37] += np.array([-2, 0])
prb_bowtie_LL.mapping[69]  += np.array([-10,2])
prb_bowtie_LL.mapping[116] += np.array([-2, 0])
prb_bowtie_LL.mapping[72]  += np.array([-10,2])
prb_bowtie_LL.mapping[65]  += np.array([-2, 0])
prb_bowtie_LL.mapping[83] += np.array([-10,2])
prb_bowtie_LL.mapping[101] += np.array([-2, 0])

prb_bowtie_LL[0] = np.array([59,  5, 52,  3])
prb_bowtie_LL[1] = np.array([60, 10, 54, 53])
prb_bowtie_LL[2] = np.array([58, 12,  4, 13])
prb_bowtie_LL[3] = np.array([11, 57,  2, 55])

prb_bowtie_LL[4] = np.array([15,  8,  1, 51])
prb_bowtie_LL[5] = np.array([63, 48, 50, 18])
prb_bowtie_LL[6] = np.array([47,  0, 34, 31])
prb_bowtie_LL[7] = np.array([61,  9, 25, 33])
prb_bowtie_LL[8] = np.array([14, 62, 22, 17])

prb_bowtie_LL[9]  = np.array([39, 19, 37, 21])
prb_bowtie_LL[10] = np.array([38, 20, 35, 36])
prb_bowtie_LL[11] = np.array([45, 44, 26, 29])
prb_bowtie_LL[12] = np.array([24,  7, 40, 27])
prb_bowtie_LL[13] = np.array([32, 16, 42, 41])
prb_bowtie_LL[14] = np.array([23, 46, 28, 43])

for prb_id_LL in range(15):
    prb_bowtie_LL[prb_id_LL+15] = prb_bowtie_LL[prb_id_LL] + 64
# prb_bowtie_LL.n_ch = 160

In [7]:
prb = prb_bowtie_LL

In [8]:
prb.show()

In [8]:
prb_v1 = probe(shank_no=1, prb_type='bow_tie')

In [9]:
prb_v1.shanks[0].l = np.array([30,31,28,29,26,27,24,25,22,23,20,21,19,18,17,16,33,32,35,34,37,36,39,38,41,40,43,42,44,45,46,47])
prb_v1.shanks[0].xl = -50.
prb_v1.shanks[0].yl = 20

In [10]:
prb_v1.shanks[0].r = np.array([48,49,50,51,53,52,55,54,57,56,59,58,61,60,63,62,15,14,13,12,10,11,8,9,6,7,4,5,2,3,0,1])
prb_v1.shanks[0].xr = 50.
prb_v1.shanks[0].yr = 20

In [11]:
prb_v1.auto_pos()

In [12]:
prb_v1.mapping

OrderedDict([(30, array([-50.,  20.])),
             (31, array([-50.,  30.])),
             (28, array([-50.,  40.])),
             (29, array([-50.,  50.])),
             (26, array([-50.,  60.])),
             (27, array([-50.,  70.])),
             (24, array([-50.,  80.])),
             (25, array([-50.,  90.])),
             (22, array([-50., 100.])),
             (23, array([-50., 110.])),
             (20, array([-50., 120.])),
             (21, array([-50., 130.])),
             (19, array([-50., 140.])),
             (18, array([-50., 150.])),
             (17, array([-50., 160.])),
             (16, array([-50., 170.])),
             (33, array([-50., 180.])),
             (32, array([-50., 190.])),
             (35, array([-50., 200.])),
             (34, array([-50., 210.])),
             (37, array([-50., 220.])),
             (36, array([-50., 230.])),
             (39, array([-50., 240.])),
             (38, array([-50., 250.])),
             (41, array([-50., 260.])),


In [13]:
for i, tetrode in enumerate(prb_v1.shanks[0].l.reshape(-1,4)):
    prb_v1[i] = tetrode
for j, tetrode in enumerate(prb_v1.shanks[0].r.reshape(-1,4)):
    prb_v1[i+j+1] = tetrode

In [14]:
np.unique(prb_v1.chs).shape[0]

64

In [15]:
prb_v1.show()

/disk0/anaconda3/lib/python3.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)


In [16]:
prb_v1.prb_view.select(0)

In [ ]:
prb_v1.save('./')

In [19]:
prb

0:[ 3  5 52 59]
1:[10 53 54 60]
2:[ 4 12 13 58]
3:[ 2 11 55 57]
4:[ 1  8 15 51]
5:[18 48 50 63]
6:[ 0 31 34 47]
7:[ 9 25 33 61]
8:[14 17 22 62]
9:[19 21 37 39]
10:[20 35 36 38]
11:[26 29 44 45]
12:[ 7 24 27 40]
13:[16 32 41 42]
14:[23 28 43 46]
15:[ 67  69 116 123]
16:[ 74 117 118 124]
17:[ 68  76  77 122]
18:[ 66  75 119 121]
19:[ 65  72  79 115]
20:[ 82 112 114 127]
21:[ 64  95  98 111]
22:[ 73  89  97 125]
23:[ 78  81  86 126]
24:[ 83  85 101 103]
25:[ 84  99 100 102]
26:[ 90  93 108 109]
27:[ 71  88  91 104]
28:[ 80  96 105 106]
29:[ 87  92 107 110]

In [16]:
len(prb.grp_dict.keys())

30

In [13]:
np.sort(prb.mapping.keys())

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127])

In [14]:
prb.show()

In [8]:
prb.save('./bow_tie_LL.json')

In [8]:
ch_list[2],ch_list[17]

NameError: name 'ch_list' is not defined

In [9]:
ch_list[120:124]

NameError: name 'ch_list' is not defined

In [7]:
prb.n_ch = 160

In [6]:
prb.chs

array([  3,   5,  52,  59,  10,  53,  54,  60,   4,  12,  13,  58,   2,
        11,  55,  57,   1,   8,  15,  51,  18,  48,  50,  63,   0,  31,
        34,  47,   9,  25,  33,  61,  14,  17,  22,  62,  19,  21,  37,
        39,  20,  35,  36,  38,  26,  29,  44,  45,   7,  24,  27,  40,
        16,  32,  41,  42,  23,  28,  43,  46,  67,  69, 116, 123,  74,
       117, 118, 124,  68,  76,  77, 122,  66,  75, 119, 121,  65,  72,
        79, 115,  82, 112, 114, 127,  64,  95,  98, 111,  73,  89,  97,
       125,  78,  81,  86, 126,  83,  85, 101, 103,  84,  99, 100, 102,
        90,  93, 108, 109,  71,  88,  91, 104,  80,  96, 105, 106,  87,
        92, 107, 110])

In [9]:
prb.mask_chs

array([  6,  30,  49,  56,  70,  94, 113, 120, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159])

In [10]:
ch_list = np.hstack((prb.chs, prb.mask_chs))

In [11]:
ch_list.shape

(160,)

In [12]:
ch_list[120:128]

array([  6,  30,  49,  56,  70,  94, 113, 120])

In [75]:
ch_dict = {}
ch_dict['refs'] = {"channels": [-2, -1, -1, -1]}
ch_dict['recording'] = {}
ch_dict['recording']['channels'] = 175*[False]
ch_dict['0'] = {}
ch_dict['0']['enabled'] = 175*[True]
ch_dict['0']['mapping'] = list(ch_list+1)
ch_dict['0']['reference'] = 175*[0]

In [76]:
import json

In [77]:
def loadmap(file, filetype='json'):
    if filetype == 'json':
        with open(file) as mapping_file:    
            data = json.load(mapping_file)
    else:
        print 'the file needs to be json'
    tetrode_ch_hash = np.array(data['0']['mapping']).reshape(-1,4) - 1
    for i, _ch_hash in enumerate(tetrode_ch_hash):
            print i, _ch_hash

In [78]:
def savemap(ch_dict, filename, filetype='json'):
    if filetype == 'json':
        with open(filename, 'w') as fp:
            json.dump(ch_dict, fp,indent=4, separators=(',', ': '))

In [79]:
loadmap('./40 tetrode_channel_map_order')

0 [68 69 74 75]
1 [70 71 72 73]
2 [32 33 40 41]
3 [34 35 42 43]
4 [36 37 44 45]
5 [38 39 46 47]
6 [6 7 8 9]
7 [ 4  5 10 11]
8 [ 2  3 12 13]
9 [ 0  1 14 15]
10 [16 17 30 31]
11 [18 19 28 29]
12 [20 21 26 27]
13 [22 23 24 25]
14 [48 49 56 57]
15 [50 51 58 59]
16 [52 53 60 61]
17 [54 55 62 63]
18 [86 87 88 89]
19 [84 85 90 91]
20 [82 83 92 93]
21 [80 81 94 95]
22 [118 119 120 121]
23 [116 117 122 123]
24 [114 115 124 125]
25 [112 113 126 127]
26 [150 151 152 153]
27 [148 149 154 155]
28 [146 147 156 157]
29 [144 145 158 159]
30 [128 129 142 143]
31 [130 131 140 141]
32 [132 133 138 139]
33 [134 135 136 137]
34 [ 96  97 110 111]
35 [ 98  99 108 109]
36 [100 101 106 107]
37 [102 103 104 105]
38 [64 65 78 79]
39 [66 67 76 77]


In [80]:
savemap(ch_dict, '/disk0/testbench/open-ephys-load/shinsuke.json')

In [26]:
loadmap('./shinsuke.json')

0 [ 3  5 52 59]
1 [10 53 54 60]
2 [ 4 12 13 58]
3 [ 2 11 55 57]
4 [ 1  8 15 51]
5 [18 48 50 63]
6 [ 0 31 34 47]
7 [ 9 25 33 61]
8 [14 17 22 62]
9 [19 21 37 39]
10 [20 35 36 38]
11 [26 29 44 45]
12 [ 7 24 27 40]
13 [16 32 41 42]
14 [23 28 43 46]
15 [ 67  69 116 123]
16 [ 74 117 118 124]
17 [ 68  76  77 122]
18 [ 66  75 119 121]
19 [ 65  72  79 115]
20 [ 82 112 114 127]
21 [ 64  95  98 111]
22 [ 73  89  97 125]
23 [ 78  81  86 126]
24 [ 83  85 101 103]
25 [ 84  99 100 102]
26 [ 90  93 108 109]
27 [ 71  88  91 104]
28 [ 80  96 105 106]
29 [ 87  92 107 110]
30 [ 6 30 49 56]
31 [ 70  94 113 120]
32 [128 129 130 131]
33 [132 133 134 135]
34 [136 137 138 139]
35 [140 141 142 143]
36 [144 145 146 147]
37 [148 149 150 151]
38 [152 153 154 155]
39 [156 157 158 159]


In [168]:
prb.show()

In [27]:
!subl ./shinsuke.json

In [46]:
with open('/disk0/testbench/open-ephys-load/bowtieprb') as mapping_file:
    data0 = json.load(mapping_file)

In [47]:
data0

{u'0': {u'enabled': [True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
 

In [48]:
with open('/disk0/testbench/open-ephys-load/shinsuke.json') as mapping_file:
    data1 = json.load(mapping_file)

In [49]:
data1

{u'0': {u'enabled': [True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
 

In [51]:
data0.keys()

[u'recording', u'0', u'refs']

In [52]:
data1.keys()

[u'recording', u'0', u'refs']

In [56]:
data0['0']['reference']

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [54]:
data1['0'].keys()

[u'enabled', u'mapping']