In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
%gui qt

In [3]:
import numpy as np
from spiketag.base import probe
from spiketag.view import probe_view

/Users/laic/Work/pydev/smart/vispy/vispy/visuals/line/line.py:392: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('color', np.float32, 4)])
/Users/laic/Work/pydev/smart/vispy/vispy/visuals/line/arrow.py:55: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('linewidth', np.float32, 1)
/Users/laic/opt/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
prb_bowtie_LL = probe(shank_no=6, prb_type='bow_tie')

prb_bowtie_LL.shanks[0].l = [59,60,10,58,12,11,57,56]
prb_bowtie_LL.shanks[0].r = [5,52,3,54,53,4,13,2,55]
prb_bowtie_LL.shanks[0].xl = -100.
prb_bowtie_LL.shanks[0].yl = 20
prb_bowtie_LL.shanks[0].xr = -80.
prb_bowtie_LL.shanks[0].yr = 5

prb_bowtie_LL.shanks[1].l = [15,63,48,47,0,61,9,14,62,6]
prb_bowtie_LL.shanks[1].r = [8, 1,51,50,18,34,31,25,33,17,22,49]
prb_bowtie_LL.shanks[1].xl = -10.
prb_bowtie_LL.shanks[1].yl = 15
prb_bowtie_LL.shanks[1].xr = 10.
prb_bowtie_LL.shanks[1].yr = 0 

prb_bowtie_LL.shanks[2].l = [39,38,20,45,44,24,7,32,16,23,46,30]
prb_bowtie_LL.shanks[2].r = [19,37,21,35,36,26,29,40,27,42,41,28,43]
prb_bowtie_LL.shanks[2].xl = 80.
prb_bowtie_LL.shanks[2].yl = 10 
prb_bowtie_LL.shanks[2].xr = 100.
prb_bowtie_LL.shanks[2].yr = -5

prb_bowtie_LL.shanks[3].l = [123,124,74,122,76,75,121,120]
prb_bowtie_LL.shanks[3].r = [69,116,67,118,117,68,77,66,119]
prb_bowtie_LL.shanks[3].xl = 350
prb_bowtie_LL.shanks[3].yl = 10
prb_bowtie_LL.shanks[3].xr = 370.
prb_bowtie_LL.shanks[3].yr = -5

prb_bowtie_LL.shanks[4].l = [79,127,112,111,64,125,73,78,126,70]
prb_bowtie_LL.shanks[4].r = [72,65,115,114,82,98,95,89,97,81,86,113]
prb_bowtie_LL.shanks[4].xl = 260.
prb_bowtie_LL.shanks[4].yl = 15
prb_bowtie_LL.shanks[4].xr = 280.
prb_bowtie_LL.shanks[4].yr = 0 

prb_bowtie_LL.shanks[5].l = [103,102,84,109,108,88,71,96,80,87,110,94]
prb_bowtie_LL.shanks[5].r = [83,101,85,99,100,90,93,104,91,106,105,92,107]
prb_bowtie_LL.shanks[5].xl = 170.
prb_bowtie_LL.shanks[5].yl = 20
prb_bowtie_LL.shanks[5].xr = 190.
prb_bowtie_LL.shanks[5].yr = 5

In [5]:
prb_bowtie_LL.auto_pos()
prb_bowtie_LL.mapping

OrderedDict([(59, array([-100.,   20.])),
             (60, array([-100.,   30.])),
             (10, array([-100.,   40.])),
             (58, array([-100.,   50.])),
             (12, array([-100.,   60.])),
             (11, array([-100.,   70.])),
             (57, array([-100.,   80.])),
             (56, array([-100.,   90.])),
             (5, array([-80.,   5.])),
             (52, array([-80.,  15.])),
             (3, array([-80.,  25.])),
             (54, array([-80.,  35.])),
             (53, array([-80.,  45.])),
             (4, array([-80.,  55.])),
             (13, array([-80.,  65.])),
             (2, array([-80.,  75.])),
             (55, array([-80.,  85.])),
             (15, array([-10.,  15.])),
             (63, array([-10.,  25.])),
             (48, array([-10.,  35.])),
             (47, array([-10.,  45.])),
             (0, array([-10.,  55.])),
             (61, array([-10.,  65.])),
             (9, array([-10.,  75.])),
             (14, array([-10.,

In [6]:
prb_bowtie_LL.mapping[5]  += np.array([-10,2])
prb_bowtie_LL.mapping[52] += np.array([-2, 0])
prb_bowtie_LL.mapping[8]  += np.array([-10,2])
prb_bowtie_LL.mapping[1]  += np.array([-2, 0])
prb_bowtie_LL.mapping[19] += np.array([-10,2])
prb_bowtie_LL.mapping[37] += np.array([-2, 0])
prb_bowtie_LL.mapping[69]  += np.array([-10,2])
prb_bowtie_LL.mapping[116] += np.array([-2, 0])
prb_bowtie_LL.mapping[72]  += np.array([-10,2])
prb_bowtie_LL.mapping[65]  += np.array([-2, 0])
prb_bowtie_LL.mapping[83] += np.array([-10,2])
prb_bowtie_LL.mapping[101] += np.array([-2, 0])

prb_bowtie_LL[0] = np.array([59,  5, 52,  3])
prb_bowtie_LL[1] = np.array([60, 10, 54, 53])
prb_bowtie_LL[2] = np.array([58, 12,  4, 13])
prb_bowtie_LL[3] = np.array([11, 57,  2, 55])

prb_bowtie_LL[4] = np.array([15,  8,  1, 51])
prb_bowtie_LL[5] = np.array([63, 48, 50, 18])
prb_bowtie_LL[6] = np.array([47,  0, 34, 31])
prb_bowtie_LL[7] = np.array([61,  9, 25, 33])
prb_bowtie_LL[8] = np.array([14, 62, 22, 17])

prb_bowtie_LL[9]  = np.array([39, 19, 37, 21])
prb_bowtie_LL[10] = np.array([38, 20, 35, 36])
prb_bowtie_LL[11] = np.array([45, 44, 26, 29])
prb_bowtie_LL[12] = np.array([24,  7, 40, 27])
prb_bowtie_LL[13] = np.array([32, 16, 42, 41])
prb_bowtie_LL[14] = np.array([23, 46, 28, 43])

for prb_id_LL in range(15):
    prb_bowtie_LL[prb_id_LL+15] = prb_bowtie_LL[prb_id_LL] + 64
# prb_bowtie_LL.n_ch = 160

In [7]:
prb = prb_bowtie_LL

In [8]:
prb.show()

## one shank v1

In [36]:
prb_v1 = probe(shank_no=1, prb_type='bow_tie')

In [37]:
elecNo = np.array([16,17,18,19,21,20,23,22,25,24,27,26,29,28,31,30,47,46,45,44,42,43,40,41,38,39,36,37,34,35,32,33,62,63,60,61,58,59,56,57,54,55,52,53,51,50,49,48,1,0,3,2,5,4,7,6,9,8,11,10,12,13,14,15])

In [38]:
# prb_v1.shanks[0].l = np.array([30,31,28,29,26,27,24,25,22,23,20,21,19,18,17,16,33,32,35,34,37,36,39,38,41,40,43,42,44,45,46,47])
prb_v1.shanks[0].l = elecNo
prb_v1.shanks[0].xl = -50.
prb_v1.shanks[0].yl = 20

In [39]:
prb_v1.shanks[0].r = elecNo + 64
prb_v1.shanks[0].xr = 50.
prb_v1.shanks[0].yr = 20

In [40]:
prb_v1.auto_pos()

In [41]:
prb_v1.mapping

OrderedDict([(16, array([-50.,  20.])),
             (17, array([-50.,  30.])),
             (18, array([-50.,  40.])),
             (19, array([-50.,  50.])),
             (21, array([-50.,  60.])),
             (20, array([-50.,  70.])),
             (23, array([-50.,  80.])),
             (22, array([-50.,  90.])),
             (25, array([-50., 100.])),
             (24, array([-50., 110.])),
             (27, array([-50., 120.])),
             (26, array([-50., 130.])),
             (29, array([-50., 140.])),
             (28, array([-50., 150.])),
             (31, array([-50., 160.])),
             (30, array([-50., 170.])),
             (47, array([-50., 180.])),
             (46, array([-50., 190.])),
             (45, array([-50., 200.])),
             (44, array([-50., 210.])),
             (42, array([-50., 220.])),
             (43, array([-50., 230.])),
             (40, array([-50., 240.])),
             (41, array([-50., 250.])),
             (38, array([-50., 260.])),


In [42]:
for i, tetrode in enumerate(prb_v1.shanks[0].l.reshape(-1,4)):
    prb_v1[i] = tetrode
for j, tetrode in enumerate(prb_v1.shanks[0].r.reshape(-1,4)):
    prb_v1[i+j+1] = tetrode

In [43]:
np.unique(prb_v1.chs).shape[0]

128

In [12]:
prb_v1.show()

/Users/laic/Work/pydev/smart/vispy/vispy/visuals/markers.py:563: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('a_edgewidth', np.float32, 1)])
/Users/laic/opt/anaconda3/lib/python3.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)


In [18]:
prb_v1.prb_view.select(1)

In [30]:
prb_v1.save('./prb_v1.prb')

In [19]:
prb

0:[ 3  5 52 59]
1:[10 53 54 60]
2:[ 4 12 13 58]
3:[ 2 11 55 57]
4:[ 1  8 15 51]
5:[18 48 50 63]
6:[ 0 31 34 47]
7:[ 9 25 33 61]
8:[14 17 22 62]
9:[19 21 37 39]
10:[20 35 36 38]
11:[26 29 44 45]
12:[ 7 24 27 40]
13:[16 32 41 42]
14:[23 28 43 46]
15:[ 67  69 116 123]
16:[ 74 117 118 124]
17:[ 68  76  77 122]
18:[ 66  75 119 121]
19:[ 65  72  79 115]
20:[ 82 112 114 127]
21:[ 64  95  98 111]
22:[ 73  89  97 125]
23:[ 78  81  86 126]
24:[ 83  85 101 103]
25:[ 84  99 100 102]
26:[ 90  93 108 109]
27:[ 71  88  91 104]
28:[ 80  96 105 106]
29:[ 87  92 107 110]

In [16]:
len(prb.grp_dict.keys())

30

In [13]:
np.sort(prb.mapping.keys())

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127])

## two shank V1

In [69]:
prb_v2 = probe(shank_no=2, prb_type='bow_tie')

In [70]:
elecNo = np.array([16,17,18,19,21,20,23,22,25,24,27,26,29,28,31,30,47,46,45,44,42,43,40,41,38,39,36,37,34,35,32,33,
                   62,63,60,61,58,59,56,57,54,55,52,53,51,50,49,48,1,0,3,2,5,4,7,6,9,8,11,10,12,13,14,15])

In [72]:
elecNo.shape

(64,)

In [73]:
elecNo_l = elecNo[:elecNo.shape[0]//2]
elecNo_l

array([32, 39, 36, 33, 37, 35, 40, 21, 41, 19, 42, 17, 34, 20, 45, 22, 38,
       16, 47, 24, 43, 18, 31, 26, 44, 23, 29, 28, 46, 25, 27, 30])

In [74]:
elecNo_r = elecNo[elecNo.shape[0]//2:]
elecNo_r

array([56, 63, 62, 59, 60, 58, 10, 55, 12, 54, 14, 53, 11, 61,  9, 50, 15,
       57,  7, 48, 13, 52,  5,  0,  8, 51,  3,  2,  6, 49,  1,  4])

In [75]:
prb_v2.shanks[0].l = elecNo_l
prb_v2.shanks[0].xl = -200.
prb_v2.shanks[0].yl = 20

In [76]:
prb_v2.shanks[0].r = elecNo_r 
prb_v2.shanks[0].xr = -100.
prb_v2.shanks[0].yr = 20

In [77]:
# prb_v1.shanks[0].l = np.array([30,31,28,29,26,27,24,25,22,23,20,21,19,18,17,16,33,32,35,34,37,36,39,38,41,40,43,42,44,45,46,47])
prb_v2.shanks[1].l = elecNo_l + 64
prb_v2.shanks[1].xl = 100.
prb_v2.shanks[1].yl = 20

In [78]:
prb_v2.shanks[1].r = elecNo_r + 64
prb_v2.shanks[1].xr = 200.
prb_v2.shanks[1].yr = 20

In [79]:
prb_v2.auto_pos()

In [80]:
prb_v2.mapping

OrderedDict([(32, array([-200.,   20.])),
             (39, array([-200.,   30.])),
             (36, array([-200.,   40.])),
             (33, array([-200.,   50.])),
             (37, array([-200.,   60.])),
             (35, array([-200.,   70.])),
             (40, array([-200.,   80.])),
             (21, array([-200.,   90.])),
             (41, array([-200.,  100.])),
             (19, array([-200.,  110.])),
             (42, array([-200.,  120.])),
             (17, array([-200.,  130.])),
             (34, array([-200.,  140.])),
             (20, array([-200.,  150.])),
             (45, array([-200.,  160.])),
             (22, array([-200.,  170.])),
             (38, array([-200.,  180.])),
             (16, array([-200.,  190.])),
             (47, array([-200.,  200.])),
             (24, array([-200.,  210.])),
             (43, array([-200.,  220.])),
             (18, array([-200.,  230.])),
             (31, array([-200.,  240.])),
             (26, array([-200.,  2

In [81]:
prb_v2.shanks[0].l

array([32, 39, 36, 33, 37, 35, 40, 21, 41, 19, 42, 17, 34, 20, 45, 22, 38,
       16, 47, 24, 43, 18, 31, 26, 44, 23, 29, 28, 46, 25, 27, 30])

In [86]:
prb_v2.shanks[0].r

array([56, 63, 62, 59, 60, 58, 10, 55, 12, 54, 14, 53, 11, 61,  9, 50, 15,
       57,  7, 48, 13, 52,  5,  0,  8, 51,  3,  2,  6, 49,  1,  4])

In [87]:
prb_v2.grp_dict

{0: array([32, 33, 36, 39]),
 1: array([21, 35, 37, 40]),
 2: array([17, 19, 41, 42]),
 3: array([20, 22, 34, 45]),
 4: array([16, 24, 38, 47]),
 5: array([18, 26, 31, 43]),
 6: array([23, 28, 29, 44]),
 7: array([25, 27, 30, 46]),
 8: array([56, 59, 62, 63]),
 9: array([10, 55, 58, 60]),
 10: array([12, 14, 53, 54]),
 11: array([ 9, 11, 50, 61]),
 12: array([ 7, 15, 48, 57]),
 13: array([ 0,  5, 13, 52]),
 14: array([ 2,  3,  8, 51]),
 15: array([ 96,  97, 100, 103]),
 16: array([ 85,  99, 101, 104]),
 17: array([ 81,  83, 105, 106]),
 18: array([ 84,  86,  98, 109]),
 19: array([ 80,  88, 102, 111]),
 20: array([ 82,  90,  95, 107]),
 21: array([ 87,  92,  93, 108]),
 22: array([120, 123, 126, 127]),
 23: array([ 74, 119, 122, 124]),
 24: array([ 76,  78, 117, 118]),
 25: array([ 73,  75, 114, 125]),
 26: array([ 71,  79, 112, 121]),
 27: array([ 64,  69,  77, 116]),
 28: array([ 66,  67,  72, 115]),
 29: array([ 65,  68,  70, 113])}

In [88]:
prb_v2.shanks[0].r.reshape(-1,4)

array([[56, 63, 62, 59],
       [60, 58, 10, 55],
       [12, 54, 14, 53],
       [11, 61,  9, 50],
       [15, 57,  7, 48],
       [13, 52,  5,  0],
       [ 8, 51,  3,  2],
       [ 6, 49,  1,  4]])

In [89]:
for i, tetrode in enumerate(prb_v2.shanks[0].l.reshape(-1,4)):
    prb_v2[i] = tetrode
for j, tetrode in enumerate(prb_v2.shanks[0].r.reshape(-1,4)):
    prb_v2[i+j+1] = tetrode
for k, tetrode in enumerate(prb_v2.shanks[1].l.reshape(-1,4)):
    prb_v2[i+j+k+2] = tetrode
for l, tetrode in enumerate(prb_v2.shanks[1].r.reshape(-1,4)):
    prb_v2[i+j+k+l+3] = tetrode

In [90]:
np.unique(prb_v2.chs).shape[0]

128

In [92]:
prb_v2

0:[32 33 36 39]
1:[21 35 37 40]
2:[17 19 41 42]
3:[20 22 34 45]
4:[16 24 38 47]
5:[18 26 31 43]
6:[23 28 29 44]
7:[25 27 30 46]
8:[56 59 62 63]
9:[10 55 58 60]
10:[12 14 53 54]
11:[ 9 11 50 61]
12:[ 7 15 48 57]
13:[ 0  5 13 52]
14:[ 2  3  8 51]
15:[ 1  4  6 49]
16:[ 96  97 100 103]
17:[ 85  99 101 104]
18:[ 81  83 105 106]
19:[ 84  86  98 109]
20:[ 80  88 102 111]
21:[ 82  90  95 107]
22:[ 87  92  93 108]
23:[ 89  91  94 110]
24:[120 123 126 127]
25:[ 74 119 122 124]
26:[ 76  78 117 118]
27:[ 73  75 114 125]
28:[ 71  79 112 121]
29:[ 64  69  77 116]
30:[ 66  67  72 115]
31:[ 65  68  70 113]

In [93]:
prb_v2.show()

/Users/laic/Work/pydev/smart/vispy/vispy/visuals/markers.py:563: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('a_edgewidth', np.float32, 1)])


In [94]:
prb_v2.save('./prb_v2.prb')

In [96]:
prb_v2.chs.shape

(128,)

## two shank V3

In [113]:
prb_v3 = probe(shank_no=2, prb_type='bow_tie')

In [114]:
elecNo = np.array([32, 39, 36, 33, 37, 35, 40, 21, 41, 19, 42, 17, 34, 20, 45, 22, 38,
                   16, 47, 24, 43, 18, 31, 26, 44, 23, 29, 28, 46, 25, 27, 30, 56, 63,
                   62, 59, 60, 58, 10, 55, 12, 54, 14, 53, 11, 61,  9, 50, 15, 57,  7,
                   48, 13, 52,  5,  0,  8, 51,  3,  2,  6, 49,  1,  4])

In [115]:
elecNo.shape

(64,)

In [116]:
elecNo_l = elecNo[:elecNo.shape[0]//2]
elecNo_l

array([32, 39, 36, 33, 37, 35, 40, 21, 41, 19, 42, 17, 34, 20, 45, 22, 38,
       16, 47, 24, 43, 18, 31, 26, 44, 23, 29, 28, 46, 25, 27, 30])

In [117]:
elecNo_r = elecNo[elecNo.shape[0]//2:]
elecNo_r

array([56, 63, 62, 59, 60, 58, 10, 55, 12, 54, 14, 53, 11, 61,  9, 50, 15,
       57,  7, 48, 13, 52,  5,  0,  8, 51,  3,  2,  6, 49,  1,  4])

In [118]:
prb_v3.shanks[0].l = elecNo_l
prb_v3.shanks[0].xl = -200.
prb_v3.shanks[0].yl = 20

In [119]:
prb_v3.shanks[0].r = elecNo_r 
prb_v3.shanks[0].xr = -100.
prb_v3.shanks[0].yr = 20

In [120]:
# prb_v1.shanks[0].l = np.array([30,31,28,29,26,27,24,25,22,23,20,21,19,18,17,16,33,32,35,34,37,36,39,38,41,40,43,42,44,45,46,47])
prb_v3.shanks[1].l = elecNo_l + 64
prb_v3.shanks[1].xl = 100.
prb_v3.shanks[1].yl = 20

In [121]:
prb_v3.shanks[1].r = elecNo_r + 64
prb_v3.shanks[1].xr = 200.
prb_v3.shanks[1].yr = 20

In [122]:
prb_v3.auto_pos()

In [123]:
prb_v3.mapping

OrderedDict([(32, array([-200.,   20.])),
             (39, array([-200.,   30.])),
             (36, array([-200.,   40.])),
             (33, array([-200.,   50.])),
             (37, array([-200.,   60.])),
             (35, array([-200.,   70.])),
             (40, array([-200.,   80.])),
             (21, array([-200.,   90.])),
             (41, array([-200.,  100.])),
             (19, array([-200.,  110.])),
             (42, array([-200.,  120.])),
             (17, array([-200.,  130.])),
             (34, array([-200.,  140.])),
             (20, array([-200.,  150.])),
             (45, array([-200.,  160.])),
             (22, array([-200.,  170.])),
             (38, array([-200.,  180.])),
             (16, array([-200.,  190.])),
             (47, array([-200.,  200.])),
             (24, array([-200.,  210.])),
             (43, array([-200.,  220.])),
             (18, array([-200.,  230.])),
             (31, array([-200.,  240.])),
             (26, array([-200.,  2

In [124]:
prb_v3.shanks[0].l

array([32, 39, 36, 33, 37, 35, 40, 21, 41, 19, 42, 17, 34, 20, 45, 22, 38,
       16, 47, 24, 43, 18, 31, 26, 44, 23, 29, 28, 46, 25, 27, 30])

In [125]:
prb_v3.shanks[0].r

array([56, 63, 62, 59, 60, 58, 10, 55, 12, 54, 14, 53, 11, 61,  9, 50, 15,
       57,  7, 48, 13, 52,  5,  0,  8, 51,  3,  2,  6, 49,  1,  4])

In [126]:
prb_v3.grp_dict

{}

In [127]:
prb_v3.shanks[0].r.reshape(-1,4)

array([[56, 63, 62, 59],
       [60, 58, 10, 55],
       [12, 54, 14, 53],
       [11, 61,  9, 50],
       [15, 57,  7, 48],
       [13, 52,  5,  0],
       [ 8, 51,  3,  2],
       [ 6, 49,  1,  4]])

In [130]:
for i, tetrode in enumerate(prb_v3.shanks[0].l.reshape(-1,4)):
    prb_v3[i] = tetrode
for j, tetrode in enumerate(prb_v3.shanks[0].r.reshape(-1,4)):
    prb_v3[i+j+1] = tetrode
for k, tetrode in enumerate(prb_v3.shanks[1].l.reshape(-1,4)):
    prb_v3[i+j+k+2] = tetrode
for l, tetrode in enumerate(prb_v3.shanks[1].r.reshape(-1,4)):
    prb_v3[i+j+k+l+3] = tetrode

In [131]:
np.unique(prb_v3.chs).shape[0]

128

In [132]:
prb_v3

0:[32 33 36 39]
1:[21 35 37 40]
2:[17 19 41 42]
3:[20 22 34 45]
4:[16 24 38 47]
5:[18 26 31 43]
6:[23 28 29 44]
7:[25 27 30 46]
8:[56 59 62 63]
9:[10 55 58 60]
10:[12 14 53 54]
11:[ 9 11 50 61]
12:[ 7 15 48 57]
13:[ 0  5 13 52]
14:[ 2  3  8 51]
15:[ 1  4  6 49]
16:[ 96  97 100 103]
17:[ 85  99 101 104]
18:[ 81  83 105 106]
19:[ 84  86  98 109]
20:[ 80  88 102 111]
21:[ 82  90  95 107]
22:[ 87  92  93 108]
23:[ 89  91  94 110]
24:[120 123 126 127]
25:[ 74 119 122 124]
26:[ 76  78 117 118]
27:[ 73  75 114 125]
28:[ 71  79 112 121]
29:[ 64  69  77 116]
30:[ 66  67  72 115]
31:[ 65  68  70 113]

In [135]:
prb_v3.show()

/Users/laic/Work/pydev/smart/vispy/vispy/visuals/markers.py:563: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('a_edgewidth', np.float32, 1)])


In [134]:
prb_v3.save('./prb_v3.prb')

In [96]:
prb_v3.chs.shape

(128,)

In [136]:
!open .