In [1]:
pwd

u'/opt/localuser/Work/pydev/spiketag/demo'

In [2]:
%load_ext autoreload

In [3]:
%autoreload 2

In [4]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [5]:
%gui qt

# load and view the probe geometry

In [6]:
from spiketag.probe import prb_bowtie_LL as prb

In [7]:
prb.show(font_size=30)

/opt/localuser/anaconda2/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)


## Sort

In [7]:
prb.fs =25000.
prb.n_ch = 160
prb.reorder_by_chip = True
prb._nchips = 5

In [8]:
from spiketag.mvc.Control import controller

In [9]:
ctrl = controller(mua_filename='/data1/n62/new_maze/vr_08092018/mua.bin',
                  spk_filename='/data1/n62/new_maze/vr_08092018/spk.bin',
                  probe=prb, binary_radix=13,
                  playground_log='/data1/n62/new_maze/vr_08092018/process.log',
                  cutoff = [-7000, 1000],
                  time_segs = [[0, 2550]],
                  session_id=14,
                  v_cutoff = 5,
                  behavior_start_time = 0
                 )

2018-08-11 23:50:19,481 - spiketag - INFO - load mua data
2018-08-11 23:50:19,653 - spiketag - INFO - #############  load data  ###################
2018-08-11 23:50:19,655 - spiketag - INFO - /data1/n62/new_maze/vr_08092018/mua.bin loaded, it contains: 
2018-08-11 23:50:19,657 - spiketag - INFO - 63983346 * 160 points (40949341440 bytes) 
2018-08-11 23:50:19,658 - spiketag - INFO - 160 channels with sampling rate of 25000.0000 
2018-08-11 23:50:19,659 - spiketag - INFO - 2559.334 secs (42.656 mins) of data
2018-08-11 23:50:19,660 - spiketag - INFO - #############################################
2018-08-11 23:50:22,226 - spiketag - INFO - reordered with nchips=5 and nch_perchip=32
2018-08-11 23:50:25,099 - spiketag - INFO - processing folder: /data1/n62/new_maze/vr_08092018/
2018-08-11 23:50:25,244 - spiketag - INFO - raw data have 2911724 spks
2018-08-11 23:50:25,245 - spiketag - INFO - ----------------success------------------
2018-08-11 23:50:25,246 - spiketag - INFO -  


In [9]:
from playground.base import logger

In [11]:
log = logger('/data1/n62/new_maze/vr_08092018/process.log')

In [21]:
log.log_sessions[14]

func level                                msg  \
2732    jovian_process_start  INFO  ---------------------------------   
2733                    info  INFO   child process calling self.run()   
2734         _jovian_process  INFO         12300, [130916, 125813, 0]   
2735         _jovian_process  INFO         12316, [130916, 125813, 0]   
2736         _jovian_process  INFO         12333, [130916, 125813, 0]   
2737         _jovian_process  INFO         12350, [130916, 125813, 0]   
2738         _jovian_process  INFO         12366, [130916, 125813, 0]   
2739         _jovian_process  INFO         12383, [130916, 125813, 0]   
2740         _jovian_process  INFO         12400, [130916, 125813, 0]   
2741         _jovian_process  INFO         12416, [130916, 125813, 0]   
2742         _jovian_process  INFO         12433, [130916, 125813, 0]   
2743         _jovian_process  INFO         12450, [130916, 125813, 0]   
2744         _jovian_process  INFO         12466, [130916, 125813, 0]   
2745         _jovian_process  INFO         12483, [130916, 125813, 0]   
2746         _jovian_process  INFO         12500, [130916, 125813, 0]   
2747         _jovian_process  INFO         12516, [130916, 125813, 0]   
2748         _jovian_process  INFO         12533, [130916, 125813, 0]   
2749         _jovian_process  INFO         12550, [130916, 125813, 0]   
2750         _jovian_process  INFO         12566, [130916, 125813, 0]   
2751         _jovian_process  INFO         12583, [130916, 125813, 0]   
2752         _jovian_process  INFO         12600, [130916, 125813, 0]   
2753         _jovian_process  INFO         12616, [130916, 125813, 0]   
2754         _jovian_process  INFO         12633, [130916, 125813, 0]   
2755         _jovian_process  INFO         12650, [130916, 125813, 0]   
2756         _jovian_process  INFO         12666, [130916, 125813, 0]   
2757         _jovian_process  INFO         12683, [130916, 125813, 0]   
2758         _jovian_process  INFO         12700, [130916, 125813, 0]   
2759         _jovian_process  INFO         12717, [130916, 125813, 0]   
2760         _jovian_process  INFO         12733, [130916, 125813, 0]   
2761         _jovian_process  INFO         12750, [130916, 125813, 0]   
...                      ...   ...                                ...   
307714       _jovian_process  INFO       5077628, [140162, 124136, 0]   
307715       _jovian_process  INFO       5077645, [140164, 124139, 0]   
307716       _jovian_process  INFO       5077661, [140166, 124142, 0]   
307717       _jovian_process  INFO       5077678, [140168, 124142, 0]   
307718       _jovian_process  INFO       5077695, [140171, 124139, 0]   
307719       _jovian_process  INFO       5077711, [140175, 124133, 0]   
307720       _jovian_process  INFO       5077728, [140179, 124129, 0]   
307721       _jovian_process  INFO       5077744, [140182, 124123, 0]   
307722       _jovian_process  INFO       5077762, [140185, 124119, 0]   
307723       _jovian_process  INFO       5077778, [140186, 124117, 0]   
307724       _jovian_process  INFO       5077795, [140186, 124114, 0]   
307725       _jovian_process  INFO       5077811, [140187, 124113, 0]   
307726       _jovian_process  INFO       5077828, [140188, 124111, 0]   
307727       _jovian_process  INFO       5077845, [140188, 124110, 0]   
307728       _jovian_process  INFO       5077861, [140189, 124108, 0]   
307729       _jovian_process  INFO       5077878, [140193, 124108, 0]   
307730       _jovian_process  INFO       5077895, [140193, 124108, 0]   
307731       _jovian_process  INFO       5077911, [140194, 124110, 0]   
307732       _jovian_process  INFO       5077928, [140194, 124110, 0]   
307733       _jovian_process  INFO       5077945, [140194, 124110, 0]   
307734       _jovian_process  INFO       5077961, [140194, 124110, 0]   
307735       _jovian_process  INFO       5077978, [140194, 124110, 0]   
307736       _jovian_process  INFO       5077994, [140194, 124110, 0]   
307737   

In [10]:
ctrl.sort()

2018-08-11 23:50:42,533 - spiketag - INFO - extract spikes from pivital meta data
2018-08-11 23:50:42,536 - spiketag - INFO - mua.tospk()
2018-08-11 23:50:44,164 - spiketag - INFO - group 0 delete 11.6313617607%(2114.0/18175.0) spks via cutoff
2018-08-11 23:50:44,168 - spiketag - INFO - group 0 delete 68.8562356018%(11059.0/16061.0) spks via speed
2018-08-11 23:50:45,165 - spiketag - INFO - group 1 delete 8.72235394721%(2244.0/25727.0) spks via cutoff
2018-08-11 23:50:45,169 - spiketag - INFO - group 1 delete 63.9356129966%(15014.0/23483.0) spks via speed
2018-08-11 23:50:48,535 - spiketag - INFO - group 2 delete 4.18103743633%(3661.0/87562.0) spks via cutoff
2018-08-11 23:50:48,552 - spiketag - INFO - group 2 delete 47.5822695796%(39922.0/83901.0) spks via speed
2018-08-11 23:50:51,628 - spiketag - INFO - group 3 delete 4.02671135232%(3220.0/79966.0) spks via cutoff
2018-08-11 23:50:51,643 - spiketag - INFO - group 3 delete 53.0529278399%(40716.0/76746.0) spks via speed
2018-08-11 23:

2018-08-11 23:52:35,317 - spiketag - INFO - spk._tofet(group_id=13, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:35,349 - spiketag - INFO - spk._tofet(group_id=14, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:35,418 - spiketag - INFO - spk._tofet(group_id=15, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:35,598 - spiketag - INFO - spk._tofet(group_id=16, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:36,222 - spiketag - INFO - spk._tofet(group_id=17, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:36,357 - spiketag - INFO - spk._tofet(group_id=18, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:36,386 - spiketag - INFO - spk._tofet(group_id=19, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:36,445 - spiketag - INFO - spk._tofet(group_id=20, method=weighted-pca, ncomp=6, whiten=False)
2018-08-11 23:52:36,759 - spiketag - INFO - spk._tofet(group_id=21, method=weighted-pca, ncomp=6, whiten

In [11]:
ctrl.show()

(5, array([18, 48, 50, 63]))


In [22]:
ctrl.model.ts

array([0.00000000e+00, 1.66691447e-02, 3.33382894e-02, ...,
       2.56063066e+03, 2.56064733e+03, 2.56066400e+03])

In [18]:
current_time = ctrl.model.mua.spk_times[ctrl.current_group][ctrl.view.spkview.selected_spk]/ctrl.model.mua.fs
ctrl.model.mua.show(prb.chs, time=current_time, span=0.5)

In [19]:
current_time

array([1574.05072])

In [24]:
ctrl.get_fields()
ctrl.plot_fields()

In [25]:
plot(ctrl.model.pos[:,0], ctrl.model.pos[:,1], '--')

In [20]:
!mkdir /data1/n62/new_maze/vr_08092018/spiketag

In [18]:
ctrl.save('/data1/n62/new_maze/vr_08092018/spiketag/place_cells')

(4, array([ 1,  8, 15, 51]))
delete (36,) spikes
delete (1,) spikes


## Sort based on previous saved spiketag

In [7]:
prb.fs =25000.
prb.n_ch = 160
prb.reorder_by_chip = True
prb._nchips = 5

In [8]:
from spiketag.mvc.Control import controller

In [9]:
ctrl = controller('/data1/spiketag_demo/mua.bin', 
                  '/data1/spiketag_demo/spk.bin', 
                  prb, spktag_filename='/data1/spiketag_demo/spiketag/test')

2018-07-17 22:01:31,397 - spiketag - INFO - load spktag file
2018-07-17 22:01:32,613 - spiketag - INFO - load mua data for wave view
2018-07-17 22:01:32,616 - spiketag - INFO - #############  load data  ###################
2018-07-17 22:01:32,618 - spiketag - INFO - /data1/spiketag_demo/mua.bin loaded, it contains: 
2018-07-17 22:01:32,620 - spiketag - INFO - 17059414 * 160 points (10918024960 bytes) 
2018-07-17 22:01:32,622 - spiketag - INFO - 160 channels with sampling rate of 25000.0000 
2018-07-17 22:01:32,624 - spiketag - INFO - 682.377 secs (11.373 mins) of data
2018-07-17 22:01:32,625 - spiketag - INFO - #############################################
2018-07-17 22:01:33,905 - spiketag - INFO - reordered with nchips=5 and nch_perchip=32
2018-07-17 22:01:37,273 - spiketag - INFO - processing folder: /data1/spiketag_demo/
2018-07-17 22:01:37,314 - spiketag - INFO - raw data have 655193 spks
2018-07-17 22:01:37,316 - spiketag - INFO - ----------------success------------------
2018-07

In [31]:
ctrl.show()

  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/t

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/localuser/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 832, in start

## spike time

In [18]:
spk_time = ctrl.model.gtimes

In [19]:
clu = ctrl.model.clu[0]

In [20]:
clu.index[1]

array([   4,  194,  206,  300,  717,  765,  791,  819,  837,  844,  884,
        963,  974, 1000, 1131, 1195, 1207, 1285, 1318, 1329, 1343, 1386,
       1485, 1488, 1490, 1508, 1531, 1779, 1891, 1953, 2353, 2540, 2615,
       2660, 2671, 2763, 2782, 2784, 2819, 2873, 2896, 2903, 2905, 2915,
       2933, 2934, 2970, 2974, 2979, 2980, 2988, 2990, 2991, 3065, 3068,
       3078, 3081, 3124, 3184, 3193, 3199, 3203, 3204, 3206, 3222, 3329,
       3670, 3720, 3748, 3775, 3795, 3808, 3844, 3872, 3949, 3994, 4071,
       4088, 4123, 4215, 4253, 4382, 4850, 4872, 5000, 5002, 5085, 5305,
       5314, 5317, 5358, 5387, 5395, 5400, 5403, 5426, 5451, 5452, 5459,
       5472, 5479, 5483, 5485, 5486, 5498, 5650])

In [24]:
ctrl.view.spkview.selected_spk

array([   4,  194,  206,  300,  717,  765,  791,  819,  837,  844,  884,
        963,  974, 1000, 1131, 1195, 1207, 1285, 1318, 1329, 1343, 1386,
       1485, 1488, 1490, 1508, 1531, 1779, 1891, 1953, 2353, 2540, 2615,
       2660, 2671, 2763, 2782, 2784, 2819, 2873, 2896, 2903, 2905, 2915,
       2933, 2934, 2970, 2974, 2979, 2980, 2988, 2990, 2991, 3065, 3068,
       3078, 3081, 3124, 3184, 3193, 3199, 3203, 3204, 3206, 3222, 3329,
       3670, 3720, 3748, 3775, 3795, 3808, 3844, 3872, 3949, 3994, 4071,
       4088, 4123, 4215, 4253, 4382, 4850, 4872, 5000, 5002, 5085, 5305,
       5314, 5317, 5358, 5387, 5395, 5400, 5403, 5426, 5451, 5452, 5459,
       5472, 5479, 5483, 5485, 5486, 5498, 5650])

In [26]:
spk_time[0][clu.index[1]]/25000.

array([  2.24868,  14.72312,  14.98536,  22.37072,  52.0672 ,  55.71692,
        66.95588,  70.75388,  74.99176,  77.56404,  94.57788,  98.79492,
        99.68668, 102.09396, 123.39484, 138.17644, 143.34944, 154.45956,
       160.65976, 164.42612, 167.9042 , 169.87572, 187.8016 , 189.54756,
       191.02852, 195.93704, 205.27016, 261.9442 , 269.19416, 274.03196,
       326.28688, 341.2738 , 345.4662 , 346.85668, 347.85908, 354.90028,
       356.80692, 357.617  , 358.7798 , 361.22756, 366.15008, 367.12976,
       368.17744, 372.2744 , 375.2562 , 375.26212, 383.878  , 385.94656,
       386.601  , 386.74452, 387.1984 , 387.3024 , 387.33016, 393.20304,
       393.26276, 393.53116, 393.72664, 397.30676, 399.93848, 401.20504,
       401.5546 , 403.58588, 403.5904 , 403.60868, 405.9426 , 409.01248,
       423.25792, 425.15292, 426.52712, 428.66288, 435.0716 , 436.62464,
       439.66552, 441.80112, 445.36852, 454.71096, 466.9398 , 467.94568,
       470.79692, 495.63668, 497.45336, 517.71364, 